### ISSUE TITLE
El control del zoom no responde "cómodamente"

### ISSUE THREAD

**Issue by iglosiggio** [HuayraLinux/huayra-visor-manual#11]
El control de zoom se agranda con el zoom (cosa que para el usuario se va a sentir rarísimo) y funciona sólo al soltar el mouse, esto último se puede palear (con el evento [input](http://stackoverflow.com/questions/18544890/onchange-event-on-input-type-range-is-not-triggering-in-firefox-while-dragging)) pero antes de eso hay que solucionar el primer punto porque sino se vuelve directamente inusable el control.

**Comment by hugoruscitti** [comment]
Sip, es cierto. Pilas-Bloques tiene un problema similar:

![screencast 2016-07-20 19-16-37](https://cloud.githubusercontent.com/assets/99183/17005119/dab77996-4eae-11e6-9d6a-0f0a78b553f7.gif)

Si el botón aumenta el zoom en pasos muy pequeños no se ve tan grave (creo).

Otra opción es hacer que los botones "+" y "-" alteren el tamaño de fuente solamente, no el zoom de nwjs, pero es un poco más laborioso. ¿cómo lo ves vos @iglosiggio?

**Comment by iglosiggio** [comment]
Estoy evaluando ambas opciones (y una extra que es usar la propiedad scale
de las transforms de css3) voy a buscar un hack alrededor del zoomlevel
para tener una versión estable y usable y después veré si se puede hacer
algo más elegante.
El 20 jul. 2016 19:23, "Hugo Ruscitti" <notifications@github.com> escribió:

Sip, es cierto. Pilas-Bloques tiene un problema similar:

[image: screencast 2016-07-20 19-16-37]
<https://cloud.githubusercontent.com/assets/99183/17005119/dab77996-4eae-11e6-9d6a-0f0a78b553f7.gif>

Si el botón aumenta el zoom en pasos muy pequeños no se ve tan grave (creo).

Otra opción es hacer que los botones "+" y "-" alteren el tamaño de fuente
solamente, no el zoom de nwjs, pero es un poco más laborioso. ¿cómo lo ves
vos @iglosiggio <https://github.com/iglosiggio>?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HuayraLinux/huayra-visor-manual/issues/11#issuecomment-234102323>,
or mute the thread

**Comment by iglosiggio** [comment]
Puse botones como en pilas-bloques y le hice la letra un poco más grande a todo, es usable la verdad.

Obvio que se podría mejorar.

**Comment by hugoruscitti** [comment]
Excelente, chequeado 👍
