### ISSUE TITLE
build error (relacionado con npm)

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-visor-manual#22]
Adjunto log: 

[huayra-visor-manual_1.5.2_amd64.build.txt](https://github.com/HuayraLinux/huayra-visor-manual/files/473057/huayra-visor-manual_1.5.2_amd64.build.txt)

**Comment by hugoruscitti** [comment]
Justo estoy haciendo cambios, fijate que el build funciona en strider:

http://ci.huayragnulinux.com.ar/huayralinux/huayra-visor-manual/

**Comment by iglosiggio** [comment]
Probaste cambiando el compilador?
