### ISSUE TITLE
resultados duplicados en la búsqueda

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-visor-manual#23]
Si buscas por una palabra. Y luego volves a buscar, no se limpia el resultado y va haciendo un append de los mismos.
![virtualbox_huayra 3 2_19_05_2017_13_34_14](https://cloud.githubusercontent.com/assets/95441/26258038/4dd546aa-3c99-11e7-96bd-5183a21df5ae.png)

**Comment by iglosiggio** [comment]
Ahí identifiqué el error, me sirvió de paso pasa hacer la búqueda muchísimo más rápida! Voy a testear que se genere el paquete correctamente y cierro el issue

**Comment by iglosiggio** [comment]
@ftoledo está cortada la luz en pizurno y no pude testear que ande todo bien, porfavor cuando puedas intentá clonar y hacer un pbuild, si anda cambiá la versión de unreleased a unstable y generá el tag
