### ISSUE TITLE
Separar en dos repositorios la generación de paquetes.

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-visor-manual#6]
Podríamos hacer un repositorio llamado pkg-huayra-visor-manual similar al resto de los paquetes.

También deberíamos crear algún comando en make para incrementar la versión usando tags para que uscan detecte correctamente la versión.

**Comment by iglosiggio** [comment]
A mí en lo personal se me hace cómodo que esté en nativo el paquete. Yo separaría el manual aparte cosa de que sea usable por apps como yelp de gnome.

**Comment by ftoledo** [comment]
Tal cual, ésta app es nativa de huayra por lo tanto no está mal que sea un paquete nativo

**Comment by hugoruscitti** [comment]
y dale...
