### ISSUE TITLE
Agregar opción para incrementar el tamaño de fuentes.

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-visor-manual#7]
Se puede usar zoomlevel como en pilas-bloques:

https://github.com/nwjs/nw.js/wiki/window#windowzoomlevel

**Comment by iglosiggio** [comment]
En 9bd96061652741e0469e3cf35e397808c8093b31 hice una implementación ultra básica, no cierro el issue porque probablemente haya cosas que mejorar

**Comment by hugoruscitti** [comment]
Entiendo que está resuelto en este otro issue: https://github.com/HuayraLinux/huayra-visor-manual/issues/11
