### ISSUE TITLE
Simplificar el arranque de la aplicación.

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-visor-manual#8]
Actualmente el archivo package.json intenta abrir el archivo "src/app.html" y este la ventana inicial. Habría que simplificar este proceso, eliminando el archivo "src/app.html" y haciendo que el archivo package.json abra directamente la ventana principal.

**Comment by iglosiggio** [comment]
En dc54ed15a271a3fbdafaa00d2dd0e55278fc255f quité el app.html. Los cambios dieron esto:
* node-init.js: Corre en contexto de node y expone un callback para el init de la aplicación
* src/init.js: Se injecta en cada página (desde package.json) y hace lo correspondiente en el init (y nada más en el init ¿Hay alguna forma mejor que injectarlo en todas?)

**Comment by iglosiggio** [comment]
En d90ca03a837064a69c299d9e9c3a3af8b878639c reparé que queden mil listeners escuchando al evento 'open' de nw.App.
