### ISSUE TITLE
Probar que la aplicación se pueda abrir en un capítulo particular desde argumentos

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-visor-manual#9]
Anteriomente, cuando usábamos el asistente de primeros pasos, existía la posibilidad de abrir el visor de manual en algunos capítulos particulares.

Si eliminamos el archivo "app/src.html" #8 esto dejaría de funcionar.

Estuvimos viendo con @iglosiggio que hay otra forma de atender los argumentos desde nodewebkit, y podría servirnos en este caso:

https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments

**Comment by iglosiggio** [comment]
Con 59506d649e0c8d69c7a679add1b18264b82750a9 cierro el issue, puede pasar más adelante que artículos con nombres __muy__ raros generen problemas y eso haría revisar src/js/init.js:54 y src/js/init.js:74
